In [1]:
from transformers import BertForSequenceClassification, BertTokenizer

C:\Users\Anith.Shatamraj\PersonalProjects\UdemyTransformers\venv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tokenizer = BertTokenizer.from_pretrained('ProsusAI/finbert')
model = BertForSequenceClassification.from_pretrained('ProsusAI/finbert')

In [3]:
sentence = [
    'what is the sentiment of this sentence? what does finbert model say about it?',
    'sales projections of Q2 seems to be good. We are expecting 30% more profits compared to last quarter',
    'sales in Q3 were disappointing. They were no where close to the projections. We encountred 5% loss compared to 30% profits in projection'
]

In [4]:
tokens = tokenizer(sentence, add_special_tokens=True, max_length=512, padding='max_length', truncation=True, return_tensors='pt')

In [8]:
tokens['input_ids'][0]

tensor([  101,  2054,  2003,  1996, 15792,  1997,  2023,  6251,  1029,  2054,
         2515, 10346,  8296,  2944,  2360,  2055,  2009,  1029,   102,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0, 

In [10]:
predictions = model(**tokens)

In [13]:
predictions[0]

tensor([[-1.2547, -0.2651,  2.2496],
        [ 2.0585, -1.5169, -1.7584],
        [-1.3399,  2.8247, -1.4145]], grad_fn=<AddmmBackward0>)

In [15]:
from torch.nn.functional import softmax
from torch import argmax

In [17]:
preds = softmax(predictions[0], dim=-1)

In [18]:
preds

tensor([[0.0271, 0.0728, 0.9001],
        [0.9524, 0.0267, 0.0209],
        [0.0151, 0.9709, 0.0140]], grad_fn=<SoftmaxBackward0>)

In [21]:
argmax(preds, dim=-1)

tensor([2, 0, 1])